# Generated by Django 3.2 on 2021-04-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(choices=[('MARGARITA', 'margarita'), ('MARINARA', 'marinara'), ('SALAMI', 'salami')], max_length=10)),
                ('size', models.CharField(choices=[('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large')], max_length=6)),
                ('count', models.IntegerField(default=1)),
                ('order_status', models.CharField(choices=[('RECIEVED', 'recieved'), ('TRANSIT', 'transit'), ('DELIVERED', 'delivered')], max_length=10)),
            ],
        ),
    ]
