# Generated by Django 3.2 on 2021-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_orders', '0004_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RECIEVED', 'recieved'), ('TRANSIT', 'transit'), ('DELIVERED', 'delivered')], default='RECIEVED', max_length=10),
        ),
    ]
